version: '3'

services:
  api:
    container_name: wongames_api
    image: jsoares1104/wongames-api:latest
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: wongames
      DATABASE_PASSWORD: wongames123
      DATABASE_NAME: wongames
      STRIPE_KEY: 'pk_test_51KVmoKJBI7gyKEoSBWwoDhbt0MljIQWR0L6KlzzMQ6pc1VAio6XAZzffxuzuUAC2Ae1Rc7rFS8l0YTRwmJ8rfNdA00IwW6YgoB'
    ports:
      - '1337:1337'
    depends_on:
      - db

  db:
    container_name: wongames_db
    image: jsoares1104/wongames-database:latest
    ports:
      - '5432:5432'
